print("Bem-vindo(a) a Calculadora de Gorjetas!")
conta = float(input("Qual foi o valor total da conta? R$: "))
gorjeta = int(input("Qual porcentagem de gorjeta você gostaria de dar? 10%, 12% ou 15%? "))
pessoas = int(input("Com quantas pessoas a conta será dividida? "))
resultado = (conta / pessoas) * (gorjeta / 100 + 1)
print("Cada pessoa deverá pagar R$: " + str(round(resultado, 2)) + " Reais!")
